export interface TopLevelConfig {
  MONGODB_URL: string;
  PAPERLESS_LOGS_BASE_URL: string;
  PORT_PAPERLESS_APPLICATIONS: string;
  PORT_PAPERLESS_AUTH: string;
  PORT_PAPERLESS_SERVICES: string;
  PORT_PAPERLESS_BANKING: string;
  PORT_PAPERLESS_NOTIFICATION: string;
  MONGODB_PAPERLESS_URL: string;
  PORT_PAPERLESS: string;
  PAPERLESS_CREDENTIAL_SECRET_KEY: string
  _JWTSECRET: string;
  _JWTEXPIREY: string;
  _TEMPSESSIONTIMEOUT: string;
  BANK_URL: string;
  OTHER_BANK_URL: string;
  WALLET_URL: string;
  REDIS_HOST: string;
  REDIS_PORT: string;
  REDIS_BASICAUTH: string;
  PWDSecretKey: string;
  PWDiv: string;
  UTILITIES_URL: string;
  DSTV_URL: string;
  DSTV_CORE_URL: string;
  DSTV_SOAP_ACTION: string;
  DSTV_BUSINESS_UNIT: string;
  DSTV_INTERFACE_TYPE: string;
  DSTV_IPADDRESS: string;
  DSTV_LANGUAGE: string;
  DSTV_VENDOR_CODE: string;
  TRAFFIC_URL: string;
  CPS_PUBLIC_ASSET_DOMAIN: string
  QR_URL: string
  QR_EXPIREY: string
  DSTV_USERNAME: string;
  DSTV_PASSWORD: string;
  DSTV_CLIENT_ID: string;
  MINIO_ENDPOINT: string;
  PAPERLESS_ASSETS_BASE_URL: string;
  PORT_MINIO: number;
  MINIO_ACCESS_KEY: string;
  MINIO_SECRET_KEY: string;
  MINIO_BUCKET_NAME: string;
  PAPERLESS_DASHEN_SMS: string;
  PAPERLESS_SMS_USERNAME: string;
  PAPERLESS_SMS_PASSWORD: string;
  KAFKA_ADDRESS: string;
  LDAP_URL: string
}
